version: '2.3'
services: 
    nginx:
        image: nginx:1.17.9-alpine
        container_name: nginx
        ports: 
            - "80:80"
            - "443:443"
        expose: 
            - '80'
            - '443'
        volumes: 
            - ./nginx/:/etc/nginx/conf.d/
            - ./www/payment/:/usr/share/nginx/html
        restart: always
    db:
        image: mysql
        container_name: mysql
        ports: 
            - '3306:3306'
        expose:
            - '3306'
        restart: always
        environment: 
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'isylzjkoot0t'
            MYSQL_ROOT_PASSWORD: 'isylzjkoot0t'
        volumes: 
            - ./mysql/data/:/var/lib/mysql 
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports: 
            - "8080:80"
        restart: always
        environment: 
            MYSQL_USER: user
            MYSQL_PASSWORD: isylzjkoot0t
            MYSQL_ROOT_PASSWORD: isylzjkoot0t
    nodejs:
        image: node:13.10.1-alpine3.10
        container_name: nodejs 
        environment: 
            NODE_ENV: production
        working_dir: /home/app/serversiderender
        restart: always
        volumes:
            - ./nodejs/:/home/app/serversiderender
        expose:
            - 8083
        ports:
            - "8083:8083"
        command: "npm run dev"