version: '2.1'
services: 
    nginx:
        image: nginx:1.17.9-alpine
        container_name: nginx
        ports: 
            - "80:80"
        volumes: 
            - ./nginx/:/etc/nginx/conf.d/
            - ./www/payment/:/usr/share/nginx/html
